module calbuild.init;

import std.file;
import std.stdio;
import std.format;

int Init() {
	if (exists("project.ysl")) {
		stderr.writeln("Project already exists here");
		return 1;
	}

	string project = "# Generated by calbuild\n";

	writeln("Creating Calbuild project");
	writef("Project name: ");
	project ~= format("set Name \"%s\"\n", readln()[0 .. $ - 1]);

	std.file.write("project.ysl", project);
	std.file.write(".gitignore", "/.calbuild\n");
	mkdir("source");
	writeln("Project created");
	return 0;
}
