module calbuild.init;

import std.file;
import std.stdio;
import std.format;

int Init() {
	if (exists("project.lua")) {
		stderr.writeln("Project already exists here");
		return 1;
	}

	string project = "-- Generated by calbuild\n";

	writeln("Creating Calbuild project");
	writef("Project name: ");
	string name = readln()[0 .. $ - 1];
	project ~= format(`set("Name", "%s")` ~ '\n', name);
	project ~= format(`project("%s", get("Dir") .. "source")` ~ '\n', name);

	std.file.write("project.lua", project);
	std.file.write(".gitignore", "/.calbuild\n");
	mkdir("source");
	writeln("Project created");
	return 0;
}
